"use client";

import { useState, useEffect, useMemo } from "react";
import MainIntro from "@/app/components/about/main_intro";
import DataTable from "@/app/components/general/data-table";
import FAQ from "@/app/components/general/faq";
import PhdObjectivesPanel from "@/app/components/phd/phd-objectives";
import Campusfacilitiescard from "@/app/components/campus-facilities/campusfacilitiescard";
import SectionHeading from "@/app/components/general/SectionHeading";
import ResearchSixGridButtons from "@/app/components/research/research_six_grid-buttons";
import CustomGallery from "@/app/components/general/gallery";
import QuickLinkCard from "@/app/components/general/quick_link_card";


const mainIntroContent = {
    title: "Energy Conservation",
    description: [
        "Kalinga University demonstrates a strong commitment to achieving Sustainable Development Goals (SDGs) through a range of institutional initiatives. In alignment with SDG 7 (Affordable and Clean Energy), the University promotes the use of renewable energy and environmentally responsible practices across the campus to reduce its carbon footprint. It regularly organises skill development and capacity-building programs and encourages interdisciplinary research and innovation to address sustainability and societal challenges. Various awareness campaigns, workshops, seminars, panel discussions, guest lectures, and community outreach activities build environmental consciousness, social responsibility, and inclusive development. ",
        "The campus has installed a 300 kWp Solar Power Plant, which has generated 125,946.60 kWh of electricity. A biogas plant generates renewable energy by converting organic waste into clean fuel. Sensor-based LED lighting systems minimise unnecessary electricity consumption. The University also organises various events, such as National Energy Conservation Day and renewable energy awareness campaigns, along with poster competitions, technical exhibitions, and student projects on green technologies. Faculty and students collaborate on projects related to improving solar panel performance, hybrid energy systems, and smart energy management. Additionally, the university conducts a Free Solar PV Installation Helper Training Program under the Green Jobs sector (NSQF Level 4) to enhance technical skills and create employment opportunities in the renewable energy sector."
    ],
    imageUrl: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-1.webp",
    imageAlt: "Energy Conservation",
};

const mainIntroContent1 = {
    title: "Energy Generated & Consumed Details",
    description: [
        "The University has installed a 300 kWp Solar Power Plant, reducing dependence on conventional electricity sources. So far, it has generated 125,946.60 kWh of electricity, contributing towards lower carbon emissions and clean energy usage on campus. Solar panels are installed on rooftops and open spaces to maximise sunlight exposure and energy efficiency."
    ],
    imageUrl: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-1-2.webp",
    imageAlt: "Energy Generated & Consumed Details",
};

const items = [
    {
        question: "Energy Consumption & Renewable Energy Statistics",
        component: (
            <div className="w-full mt-4">
                <DataTable
                    columns={[
                        { key: "year", label: "Financial Year", widthPx: 120 },
                        { key: "totalConsumed", label: "Total Electricity Consumed (Grid+RE)", widthPx: 250 },
                        { key: "reInstalled", label: "Total Renewable Energy (RE) Power Installed (Solar + Wind + Others)", widthPx: 280 },
                        { key: "reGenerated", label: "Total Electricity Generated by RE Technology (Solar + Wind + Others)", widthPx: 280 },
                        { key: "builtUpArea", label: "Total Built-up Area", widthPx: 200 }
                    ]}
                    data={[
                        { year: "Unit", totalConsumed: "kWh", reInstalled: "kWp", reGenerated: "kWh", builtUpArea: "Sq.ft" },
                        { year: "2024-2025", totalConsumed: "2441.75", reInstalled: "300", reGenerated: "93936.10", builtUpArea: "829921" },
                        { year: "2023-2024", totalConsumed: "3943.3", reInstalled: "300", reGenerated: "125946.60", builtUpArea: "829921" },
                        { year: "2022-2023", totalConsumed: "119.86", reInstalled: "300", reGenerated: "97119.11", builtUpArea: "829921" }
                    ]}
                    overflowX={true}
                    disableContainer={true}
                    className="shadow-none border border-gray-100"
                />
            </div>
        )
    }
];

const hospitalMoUs = [
    { id: 1, text: "City Eye Care Hospital", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/good-health-well-being/MoU+-+City+Eye+Care+Hospital_compressed.pdf" },
    { id: 2, text: "NH MMI Hospital", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/good-health-well-being/MoU+-+NH+MMI+Hospital_compressed.pdf" },
    { id: 3, text: "Ramkrishna Care Hospital", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/good-health-well-being/MoU+-+Ramkrishna+Care+Hospital+Raipur_compressed.pdf" },
    { id: 4, text: "Saptgiri Hospital", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/good-health-well-being/MoU+-+Saptgiri+Hospital_compressed.pdf" },
    { id: 5, text: "Shri Ganesh Vinayak Eye Hospital", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/good-health-well-being/MoU+-+Shri+Ganesh+Vinayak+Eye+Hospital_compressed.pdf" },
    { id: 6, text: "Urmila Memorial Hospital", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/good-health-well-being/MoU+-+Urmila+Memorial+Hospital(pdfgear.com).pdf" },
    { id: 7, text: "VY Hospital", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/good-health-well-being/MoU+-+VY+Hospital+Kamal+Vihar+Raipur(pdfgear.com).pdf" },
];

const conservationReports = [
    { id: 1, text: "Energy Conservation Measures", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/ENERGY_1.pdf" },
    { id: 2, text: "Green Audit Report (25.02.2023)", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/GREENE_1.pdf" },
    { id: 3, text: "Energy Audit Report (FY 2021-22)", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/GREENE_3.pdf" },
    { id: 4, text: "Energy Audit Report (FY 2020-21)", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/GREENE_2_compressed.pdf" },
    { id: 5, text: "Energy Audit Manual", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/KU_ENE_1.PDF" },
    { id: 6, text: "Green Audit / Environmental Audit Manual", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/KU_ENV_1.PDF" },
    { id: 7, text: "MoU Signed with New Gurukul Education Society (NGES)", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/MOUWIT_1.PDF" },
    { id: 8, text: "Policy Guidelines For Environmental Sustainability", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/POLICY_1.pdf" },
    { id: 9, text: "Geo-Tagged Photos", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/Geo-Tagged+Photos.pdf" },
];

const eventReports = [
    { id: 1, text: "Expert Talk on “Electric Vehicles: Modern Technologies and Trends (EBLU)”", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/Expert+Talk+-+Electric+Vehicle+(eblu)+2025.pdf" },
    { id: 2, text: "Guest Lecture on “Heat Transfer Through Finite Difference”", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/Expert+Talk+-+Heat+Transfer+Through+Finite.pdf" },
    { id: 3, text: "Guest Lecture on “Power System Protection”", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/Guest+Lecture+-+Power+System+Protection+-+2025.pdf" },
    { id: 4, text: "Guest Lecture on “Solar Power Generation”", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/Guest+Lecture+-+Solar+Power+Generation+-+2026.pdf" },
    { id: 5, text: "International Conference on “Emerging Technologies for Sustainable Development” (ICETSD-2025)", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/International+Conference+ICETSD-2025.pdf" },
];

const policyDocuments = [
    { id: 1, text: "Policy on ‘Energy Conservation’", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/office-orders/1-Policy-Energy-Conservation.pdf" },
    { id: 2, text: "Policy on ‘Electricity Overuse and Misuse’", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/office-orders/2-Policy-Electrictiy-Overuse-and-Misuse.pdf" },
    { id: 3, text: "Framework on ‘Cooling & Heating Energy efficiency’", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/office-orders/9-Framework-Cooling-Heating-Energy-Efficiency.pdf" },
    { id: 4, text: "Office Order on SDG Policies", url: "https://cdn.kalingauniversity.ac.in/sdg-cell/office-orders/Office-Order-on-SDG-Policies.pdf" },
];


const cards = [
    {
        title: "Solar Power Systems – Rooftop Solar Energy",
        description:
            "The University has installed a 300 kWp Solar Power Plant, reducing dependence on conventional electricity sources. So far, it has generated 125,946.60 kWh of electricity, contributing towards lower carbon emissions and clean energy usage on campus. Solar panels are installed on rooftops and open spaces to maximise sunlight exposure and energy efficiency. The University actively promotes the usage of renewable energy through various skill development programs, research and awareness activities.This initiative not only lowered electricity expenses but also proved our commitment to adopting green technology.",
        imageSrc: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-1.webp",
        logoSrc: "",
        subtitle: "SOLAR POWER SYSTEMS",
        link: "#",
    },
    {
        title: "Biogas Plant",
        description:
            "For efficient waste management, the University has installed a biogas plant on campus that converts organic and food waste generated from hostels and other campus areas into renewable energy. The biogas produced is used as a clean fuel, reducing the dependence on conventional fuels. The plant also produces nutrient-rich slurry, an organic fertiliser used in gardening and landscaping purposes, promoting sustainable resource usage and a circular approach towards waste management.",
        imageSrc: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-1-1.webp",
        logoSrc: "",
        subtitle: "BIOGAS PLANT",
        link: "#",
    },
    {
        title: "Sensor-Based LED Lighting Systems",
        description:
            "The university has installed sensor-based LED lighting systems in several campus buildings and common areas. These smart lighting systems automatically switch on or off based on human movement and ambient light conditions, reducing unnecessary lighting consumption while maintaining adequate lighting across the campus.",
        imageSrc: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-1-2.webp",
        logoSrc: "",
        subtitle: "SENSOR-BASED LIGHTING",
        link: "#",
    },
    {
        title: "Centre of Excellence for Sustainable Transportation and Green Campus Initiatives",
        description:
            "The institution has established a Centre of Excellence dedicated to promoting sustainable and innovative practices across campus. As a key initiative, an eBlu Electric Vehicle (EV) has been introduced to create awareness about eco-friendly and energy-efficient transportation systems. The university actively encourages staff members to adopt carpooling practices, helping to reduce fuel consumption, traffic congestion, and carbon emissions. Additionally, well-organized bus facilities are provided to ensure safe, reliable, and convenient commuting for staff. These combined efforts demonstrate the institution’s strong commitment to environmental responsibility, energy conservation, and building a greener, more sustainable campus culture. ",
        imageSrc: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy Conservation/kalinga-sdg-energy.png",
        logoSrc: "",
        subtitle: "SENSOR-BASED LIGHTING",
        link: "#",
    }
];

const phdObjectives = [
    { item: "Energy Conservation Measures" },
    { item: "Green Audit Report (25.02.2023)" },
    { item: "Energy Audit Report (FY 2021-22)" },
    { item: "Energy Audit Report (FY 2020-21)" },
    { item: "Energy Audit Manual" },
    { item: "Green Audit / Environmental Audit Manual" },
    { item: "MoU Signed with New Gurukul Education Society (NGES)" },
    { item: "Policy Guidelines For Environmental Sustainability" },
    { item: "Geo-Tagged Photos" },
];

const galleryImages = [
    { id: 1, image: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-1.webp", alt: "Energy Conservation 1" },
    { id: 2, image: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-2.webp", alt: "Energy Conservation 2" },
    { id: 3, image: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-3.webp", alt: "Energy Conservation 3" },
    { id: 4, image: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-4.webp", alt: "Energy Conservation 4" },
    { id: 5, image: "https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-5.webp", alt: "Energy Conservation 5" },
];



export default function GreenCampusPage() {
    return (
        <>
            <MainIntro
                title={mainIntroContent.title}
                description={mainIntroContent.description}
                imageUrl={mainIntroContent.imageUrl}
                imageAlt={mainIntroContent.imageAlt}
                showKnowMore={true}
                initialVisibleParagraphs={1}
                knowMoreLabel="Read More"
                sectionClassName="bg-white"
            />

            <FAQ
                items={items}
                title=""
                showHeading={false}
                variant="default"
                pyClassName="py-8"
            />
            <SectionHeading title="Our Initiatives"
                titleClassName="text-center mt-10" />
            <div className="mt-4">
                <Campusfacilitiescard
                    title=""
                    cards={cards}
                    showKnowMore={false}
                    titleClassName="hidden"
                />
            </div>

            {/* <PhdObjectivesPanel
                title="Energy Conservation Reports"
                subtitle=""
                imageSrc="https://cdn.kalingauniversity.ac.in/sdg-cell/Energy+Conservation/s-1-1.webp"
                phdObjectives={phdObjectives}
            /> */}
            <div className="container mx-auto mt-16 px-4">
                <SectionHeading
                    title="Energy Conservation Reports"
                    description="Access detailed reports and documentation related to energy efficiency and renewable energy initiatives at Kalinga University."
                    titleClassName="text-center"
                />
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 mt-10">
                    {conservationReports.map((report) => (
                        <QuickLinkCard
                            key={report.id}
                            title={report.text}
                            description=""
                            showReadMore={false}
                            descriptionContainerClassName=""
                            href={report.url}
                            fullCardLink={report.url !== "#"}
                        />
                    ))}
                </div>
            </div>

            <div className="mt-10">
                <SectionHeading
                    title="Event Reports"
                    description=""
                    titleClassName="text-center"
                />
            </div>
            <ResearchSixGridButtons
                buttons={eventReports}
            />

            <div className="mt-10">
                <SectionHeading
                    title="Policies and Office Orders"
                    description=""
                    titleClassName="text-center"
                />
            </div>
            <ResearchSixGridButtons
                buttons={policyDocuments}
            />

            <CustomGallery
                images={galleryImages}
                title="Glimpses of Our Energy Conservation Initiatives"
            />
        </>
    );
}